import { type Actor } from "../as/actor"
import { Activity } from "../as/activity"
import { Collection } from "../as/collection"
import { type IActivityHandler, type ILastMessageGetterSetter } from "./interfaces"
import { loadCollectionAfter } from "../as/loaders"

// Receiver service receives messages from an ActivityPub actor and forwards them
// to the MLS client
export class Receiver {

	#messagesUrl: string = "" // endpoint for the actor's emissary:messages or plain messages collection: uwuwu owo
	#eventSource?: EventSource // EventSource for listening to server-sent events (SSE)
	#activityHandler: IActivityHandler // list of registered message handlers
	#lastMessage: ILastMessageGetterSetter // handler function for getting/setting the last message ID
	#generatorId: string // ID of this MLS client, used for the generator field of outgoing messages
	#polling: boolean // Pseudo-lock to prevent simultaneous polls
	#pollAgain: boolean // Indicates that one or more messages were received during a poll, so poll again after the current poll finishes

	// constructor initializes the Receiver with the actor's ID and messages URL
	constructor() {
		this.#activityHandler = async (activity: Activity) => { }
		this.#lastMessage = async (messageId?: string) => { return "" }
		this.#polling = false
		this.#pollAgain = false
		this.#generatorId = ""
	}

	// setActor configures the Receiver with the given Actor's information,
	// once it has been loaded from the network.
	setActor(actor: Actor) {
		const { url } = actor.messages()
		this.#messagesUrl = url
	}

	// start begins polling for new messages and processing them with the registered handlers
	async start(generatorId: string, activityHandler: IActivityHandler, lastMessage: ILastMessageGetterSetter) {

		// Set the handler function to be called with each new message
		this.#activityHandler = activityHandler
		this.#lastMessage = lastMessage
		this.#generatorId = generatorId

		// Poll the server on start
		this.#poll()

		// If possible, listen for server-sent-events (SSE) from the server
		const collection = await new Collection().fromUrl(this.#messagesUrl)
		const sseEndpoint = collection.eventStream()

		if (sseEndpoint != "") {
			this.#eventSource = new EventSource(sseEndpoint, { withCredentials: true })
			this.#eventSource.onmessage = () => {
				this.#poll()
			}
		}
	}

	stop() {
		if (this.#eventSource) {
			this.#eventSource.close()
		}
	}

	// poll retrieves new messages from the messages collection and calls the
	// onMessage callback for each new message
	async #poll() {

		// If already polling, set #pollAgain flag and exit.
		if (this.#polling) {
			this.#pollAgain = true
			return
		}

		// Set the "lock" to prevent simultaneous polls
		this.#polling = true

		// Fetch NEW messages from the server
		let lastMessageId = await this.#lastMessage()
		const collection = await loadCollectionAfter(this.#messagesUrl, lastMessageId)

		// Process each activity sequentially
		for await (const activity of collection.rangeActivities()) {

			console.log("Receiver: ", activity.toObject())
			lastMessageId = activity.id()

			// Do not process messages generated by this client
			if (activity.instrument() === this.#generatorId) {
				console.log("Receiver: Skipping message generated by this client.")
				continue
			}

			try {
				// Process the activity with the registered handler function
				await this.#activityHandler(activity)

			} catch (error) {
				console.error("Receiver.#poll: Unable to process incoming message:", activity.toJSON(), error)
			}
		}

		// Update the last message ID after processing all messages
		await this.#lastMessage(lastMessageId)

		// Release the "lock"
		this.#polling = false

		// Re-run poll if we received any messages while we were polling
		if (this.#pollAgain) {
			this.#pollAgain = false
			this.#poll()
		}
	}

}
