import { type ClientState } from "ts-mls"
import type { Contact } from "./contact"

// Group represents a group record in memory
export type Group = {
	id: string
	stateId: "IMPORTANT" | "ACTIVE" | "ARCHIVED" | "CLOSED"
	name: string        // Custom name assigned by the user (not synchronized)
	defaultName: string // Default name generated by the system based on the members of the group
	summary: string // Custom value assigned by the user (not synchronized)
	tags: string[]      // Custom values assigned by the user (not synchronized)
	lastMessage: string // The content of the last message in the group (synchronized with the server)
	members: string[]
	contacts: Contact[]
	createDate: number
	updateDate: number
	readDate: number
	unread: boolean
}

// EncryptedGroup extends Group with additional properties related to encryption state
export type EncryptedGroup = Group & {
	clientState: ClientState
}

export function NewGroup(): Group {
	return {
		id: "uri:uuid:" + crypto.randomUUID(),
		stateId: "ACTIVE",
		name: "",
		defaultName: "",
		summary: "",
		tags: [],
		lastMessage: "",
		members: [],
		contacts: [],
		createDate: Date.now(),
		updateDate: Date.now(),
		readDate: 0,
		unread: false,
	}
}

export function groupIsEncrypted(group: Group | EncryptedGroup): group is EncryptedGroup {
	return (group as EncryptedGroup).clientState !== undefined
}

export function groupNotEncrypted(group: Group | EncryptedGroup): group is Group {
	return (group as EncryptedGroup).clientState === undefined
}
