import { type ClientState } from "ts-mls"
import type { Contact } from "./contact"

// GroupState enumerates the lifecycle states of a Group
export type GroupState = "WELCOME" | "IMPORTANT" | "ACTIVE" | "ARCHIVED" | "CLOSED"

// GroupCodec enumerates the message encoding schemes supported by a Group
export type GroupCodec = "PLAINTEXT" | "MLS"

// Group represents a group record in memory
export type Group = {
	id: string
	stateId: GroupState
	codec: GroupCodec
	name: string          // Custom name assigned by the user (not synchronized)
	defaultName: string   // Default name generated by the system based on the members of the group
	summary: string       // Custom value assigned by the user (not synchronized)
	tags: string[]        // Custom values assigned by the user (not synchronized)
	createdById: string    // Actor ID of the user who welcomed us to this group
	lastMessageId: string // The ID of the most recent message in the group (synchronized with the server)
	lastMessage: string   // The content of the last message in the group (synchronized with the server)
	members: string[]     // Actor IDs of all members of the group
	contacts: Contact[]   // Contact information for all members of the group
	createDate: number    // Unix epoch (in milliseconds)
	updateDate: number    // Unix epoch (in milliseconds)
	readDate: number      // Unix epoch (in milliseconds)
	unread: boolean       // TRUE if there are message in this group that have not been read. (synchronized with the server)
}

// EncryptedGroup extends Group with additional properties related to encryption state
export type EncryptedGroup = Group & {
	clientState: ClientState
}

export function NewGroup(codec: GroupCodec): Group {

	return {
		id: "uri:uuid:" + crypto.randomUUID(),
		stateId: "WELCOME",
		codec: codec,
		name: "",
		defaultName: "",
		summary: "",
		tags: [],
		createdById: "",
		lastMessageId: "",
		lastMessage: "",
		members: [],
		contacts: [],
		createDate: Date.now(),
		updateDate: Date.now(),
		readDate: 0,
		unread: false,
	}
}

export function groupIsEncrypted(group: Group | EncryptedGroup): group is EncryptedGroup {
	return (group.codec === "MLS")
}

// groupColor returns the canonical accent color for a group: gray for a pending
// (WELCOME) invitation, blue for an encrypted group, and gold for a plaintext
// group. Returns a CSS color value (a var() reference or a literal), suitable for
// both `background-color` (avatars) and the `--group-highlight-color` custom
// property (focus outlines, accents). Single source of truth for group coloring.
export function groupColor(group: Group | EncryptedGroup): string {

	if (group.stateId == "WELCOME") {
		return "var(--gray50)"
	}

	if (groupIsEncrypted(group)) {
		return "var(--blue50)"
	}

	return "#F2C94C"
}

// filterAndSortGroups returns the groups that include EVERY one of the given tags
// and match one of the given stateIds, sorted with IMPORTANT groups first and then
// by updateDate descending within each tier. Empty `tags` / `stateIds` mean "do not
// filter on that field".
//
// Groups in the WELCOME state are always included when filtering by state: a pending
// invitation should surface no matter which filter is selected, so whenever stateIds
// are provided, WELCOME is implicitly added to them.
//
// This is the pure core of Database.searchGroups (extracted so it can be tested
// without IndexedDB).
export function filterAndSortGroups(groups: Group[], tags: string[], stateIds: GroupState[] = []): Group[] {

	const effectiveStateIds = (stateIds.length === 0) ? [] : [...stateIds, "WELCOME" as GroupState]

	return groups
		.filter(g => tags.every(tag => g.tags.includes(tag)))
		.filter(g => effectiveStateIds.length === 0 || effectiveStateIds.includes(g.stateId))
		.sort((a, b) => {

			if (a.stateId === "IMPORTANT") {
				if (b.stateId !== "IMPORTANT") {
					return -1
				}
			} else if (b.stateId === "IMPORTANT") {
				return 1
			}

			// Within the same tier, sort by updateDate descending
			return b.updateDate - a.updateDate
		})
}
