import { type ClientState } from "ts-mls"
import type { Contact } from "./contact"

// Group represents a group record in memory
export type Group = {
	id: string
	stateId: "WELCOME" | "IMPORTANT" | "ACTIVE" | "ARCHIVED" | "CLOSED"
	codec: "PLAINTEXT" | "MLS"
	name: string          // Custom name assigned by the user (not synchronized)
	defaultName: string   // Default name generated by the system based on the members of the group
	summary: string       // Custom value assigned by the user (not synchronized)
	tags: string[]        // Custom values assigned by the user (not synchronized)
	createdById: string    // Actor ID of the user who welcomed us to this group
	lastMessageId: string // The ID of the most recent message in the group (synchronized with the server)
	lastMessage: string   // The content of the last message in the group (synchronized with the server)
	members: string[]     // Actor IDs of all members of the group
	contacts: Contact[]   // Contact information for all members of the group
	createDate: number    // Unix epoch (in milliseconds)
	updateDate: number    // Unix epoch (in milliseconds)
	readDate: number      // Unix epoch (in milliseconds)
	unread: boolean       // TRUE if there are message in this group that have not been read. (synchronized with the server)
}

// EncryptedGroup extends Group with additional properties related to encryption state
export type EncryptedGroup = Group & {
	clientState: ClientState
}

export function NewGroup(codec: "PLAINTEXT" | "MLS"): Group {

	return {
		id: "uri:uuid:" + crypto.randomUUID(),
		stateId: "WELCOME",
		codec: codec,
		name: "",
		defaultName: "",
		summary: "",
		tags: [],
		createdById: "",
		lastMessageId: "",
		lastMessage: "",
		members: [],
		contacts: [],
		createDate: Date.now(),
		updateDate: Date.now(),
		readDate: 0,
		unread: false,
	}
}

export function groupIsEncrypted(group: Group | EncryptedGroup): group is EncryptedGroup {
	return (group.codec === "MLS")
}
